/*
    	1. SUB-QUERY : IS THE NESTED QUERY (QUERY INSIDE A QUERY)
		
			Q1--OUTER QUERY / MAIN QUERY (Q2 (Q3)) --INNER QUERIES


	2. IMPORTANT OPERATORS / CONNECTORS USED WITH SUB-QUERIES
		0. =: USED TO COMPARE ONE VALUE AT A TIME, 9, AMAN, 10.876
		1. IN OPERATOR: WHERE CITY IN ('AGRA', 'DELHI','MUMBAI')
		2. NOT IN: 
		3. ANY: OR OPERTOR
		4. ALL: AND OPERATOR


	3. TYPES OF SUB-QUERIES:
		1. SCALER SUB-QUERY: WHICH RETURN ONLY ONE VALUE. 9, AMAN, NULL
			OPERATORS: ARITEMETIC OPERATORS: <,>,<=,>=, != (<>)
			
		2. MULTI-VALUED / MULTI-ROW SUB-QUERY:
			WHICH RETURNS MULTIPLE ROWS AT A TIME
			OPERATORS: IN, NOT IN, ANY, ALL

		3. SELF-CONTAINED SUB-QUERY:
			WHICH IS NOT DEPENDENT ON OUTER QUERY

		4. CO-RELATED SUB-QUERY:
			WHICH IS DEPENDENT

*/










CREATE TABLE MyEmployees (
    EmpId INT PRIMARY KEY IDENTITY(1,1),
    EmpName VARCHAR(50),
    Gender VARCHAR(10),
    Salary INT,
    City VARCHAR(50),
    Dept_id INT
);



INSERT INTO MyEmployees (EmpName, Gender, Salary, City, Dept_id)
VALUES
('Amit', 'Male', 50000, 'Delhi', 2),
('Priya', 'Female', 60000, 'Mumbai', 1),
('Rajesh', 'Male', 45000, 'Agra', 3),
('Sneha', 'Female', 55000, 'Delhi', 4),
('Anil', 'Male', 52000, 'Agra', 2),
('Sunita', 'Female', 48000, 'Mumbai', 1),
('Vijay', 'Male', 47000, 'Agra', 3),
('Ritu', 'Female', 62000, 'Mumbai', 2),
('Alok', 'Male', 51000, 'Delhi', 1),
('Neha', 'Female', 53000, 'Agra', 4),
('Simran', 'Female', 33000, 'Agra', 3);




--                           SELECTING 2ND HIGHEST SALARY 
SELECT MAX(Salary) AS SECOND_HIGHEST FROM MyEmployees WHERE Salary NOT IN
(SELECT MAX(Salary) FROM MyEmployees);


SELECT * FROM MyEmployees
WHERE Dept_id IN 
(SELECT ID FROM DEPT WHERE Dept = "Accounts";


/*
NOTE: ::   WHICHEVER COLUMN USED WITH WHERE CLAUSE , WILL BE USED IN SELECT SQ
*/


--MULTI VALUED SUB QUERY: RETURN MULTIPLE ROWS
SELECT * FROM MyEmployees WHERE EmpName IN 
(SELECT * FROM MyEmployees WHERE Gender='Male');


SELECT * FROM MyEmployees
WHERE EmpId NOT IN

(SELECT * FROM MyEmployees where COUNT(EmpId)


	



	-- MEDIUM QUESTION

CREATE TABLE TBL_PRODUCTS
(
	ID INT PRIMARY KEY IDENTITY,
	[NAME] NVARCHAR(50),
	[DESCRIPTION] NVARCHAR(250) 
)

CREATE TABLE TBL_PRODUCTSALES
(
	ID INT PRIMARY KEY IDENTITY,
	PRODUCTID INT FOREIGN KEY REFERENCES TBL_PRODUCTS(ID),
	UNITPRICE INT,
	QUALTITYSOLD INT
)

INSERT INTO TBL_PRODUCTS VALUES ('TV','52 INCH BLACK COLOR LCD TV')
INSERT INTO TBL_PRODUCTS VALUES ('LAPTOP','VERY THIIN BLACK COLOR ACER LAPTOP')
INSERT INTO TBL_PRODUCTS VALUES ('DESKTOP','HP HIGH PERFORMANCE DESKTOP')


INSERT INTO TBL_PRODUCTSALES VALUES (3,450,5)
INSERT INTO TBL_PRODUCTSALES VALUES (2,250,7)
INSERT INTO TBL_PRODUCTSALES VALUES (3,450,4)
INSERT INTO TBL_PRODUCTSALES VALUES (3,450,9)


SELECT *FROM TBL_PRODUCTS
SELECT *FROM TBL_PRODUCTSALES



SELECT [NAME] AS PRODUCT_NAME
(S
